import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import { LayoutProps } from "@/lib/@types/types"
import "@/ui/globals.css"
import { Header } from "@/ui/header"
import { Footer } from "@/ui/footer"

const poppins = Poppins({
    weight: ["400", "500", "600", "700"],
    subsets: ["latin"],
    variable: "--font-poppins",
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({ children }: LayoutProps) {
    return (
        <html lang="en">
            <body
                className={`${poppins.className} relative antialiased overflow-x-hidden scroll:w-1.5 track:my-1 thumb:rounded thumb:bg-black`}
            >
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    )
}
