name: ci

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm lint

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - name: set up environment variables
        run: |
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env.local
      - run: pnpm build

  deploy-to-development:
    needs: build
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.base_ref == 'master'
    steps:
      - run: echo "Deploying to development"

  deploy-to-production:
    needs: build
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.base_ref == 'master' && startsWith(github.head_ref, 'release/')
    steps:
      - run: echo "Deploying to production"
